spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: Chitti@4
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
